name: build

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '>16'
      - name: Install Deps
        run: npm i
      - name: Build
        run: npm run build
      - name: Make fresh gh-pages branch
        run: |
          echo "git branch -D gh-pages; exit 0" > tmp.sh
          chmod +x tmp.sh
          ./tmp.sh
          rm tmp.sh
          git checkout -b gh-pages;
          git push -u origin gh-pages --force;
      - name: Move dist to current dir
        run: |
          rm -rf node_modules index.html package.json README.md svelte.config.js tsconfig.json tsconfig.nodejson vite.config.ts;
          mv dist/* ./;
      - name: Commit
        run: |
          git add .
          git commit -m "ci: Upload new branch"
          git push -u origin gh-pages
